### ISSUE TITLE
Cancelling game download prior to completion does not clean up partially downloaded chunks of the game archive

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [CollapseLauncher/Hi3Helper.Http#3]
**Describe the bug**
When downloading a game archive, multiple files are created as the game is downloaded. These files are later merged into one, but if the download process is cancelled before that, the remaining chunks should be deleted as well. However, this does not happen due to these files still being used by the application.

**To Reproduce**
1. Begin a fresh download of the game
2. Cancel the download
3. Check the download directory - the partially downloaded files still remain

**Expected behavior**
Calling `DeleteMultisessionFiles()` should ensure or wait for the release of these files and then delete them. Currently, it simply ignores any exceptions when it tries to delete the files.

**Screenshots**
I've added a simple debug output to the `DeleteMultisessionFiles()` function, which made it clear what the issue is.
![image](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/assets/12040085/87bb5b87-bd68-4c5e-8945-9a2acfab03f9)

**Comment by neon-nyan** [comment]
Hi,
This issue should have been fixed in the latest commit. I also pushed a PR to apply fixes on your project here: https://github.com/BuIlDaLiBlE/BetterHI3Launcher/pull/77

Closing this issue for now.
